[project]
name = "band-robust-framework"
authors = ["Band Financial Technologies"]
description = "A decentralized financial management platform for music groups"
telemetry = false
requirements = []
[contracts.band-shared-financials]
path = "contracts/band-shared-financials.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
